### ISSUE TITLE
C. Link als SVG

### ISSUE THREAD

**Issue by APfeifer1** [janek26/ByteFiddler#16]
Carsten Link als SVG für das Guide Tutorial.

**Comment by APfeifer1** [comment]
@janek26 Kannst du vielleicht die Grafik von deinem Projekt als Beispiel hier verlinken, damit @PetraJanssen ungefähr eine Vorstellung hat?

**Comment by janek26** [comment]
@APfeifer1 da es Open Source ist und das Produkt von meinem Kunden noch nicht auf dem Markt, nein.

**Comment by PetraJanssen** [comment]
Diese beiden Bilder stehen zur Verfügung. Beginne ab Montag Abend. 

http://www.hs-emden-leer.de/no_cache/hochschule/beschaeftigte.html?tx_wtdirectory_pi1%5Bshow%5D=536

http://www.technik-emden.de/~clink/
